CREATE TABLE TABG (
	V1 CHAR (20),
	V2 VARCHAR (20),
	V3 INT PRIMARY KEY
);
INSERT INTO TABG VALUES ('MAUA', 'COMP', 10);
INSERT INTO TABG VALUES ('ABC', 'XY', 23);
INSERT INTO TABG VALUES ('ANA', 'PAULO', 25);
INSERT INTO TABG VALUES ('PEDRO', 'JOSE', 34);
INSERT INTO TABG VALUES ('SOUZA', 'IVO', 5);